### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by 377fsq** [DocF/multispectral-object-detection#12]
Can you  provide image file structure of LLVIP？

**Comment by DocF** [comment]
You need to convert all annotations to YOLOv5 format.

Refer: https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data

**Comment by 377fsq** [comment]
Thanks for your answer, I have finished the training. But there are some questions. I used the yolov5l_fusion_transformerx3_llvip.yaml to train with default parameters, but the training results did not reach the values shown in your paper. My result mAP50: 0.965 mAP75: 0.709 mAP: 0.624 GPU: 3090Ti batch_size: 16. I want to know whether add other training strategies?

**Comment by DocF** [comment]
First, my input image size is 1024×1024.
Second, I tested the` best.pt`.

**Comment by 377fsq** [comment]
Thank you, I will try again.

**Comment by nineRishav** [comment]
Hi @377fsq , 

I need you help in running the project. I wanted to train, test the model.
But, I am facing issue in mentioning the path of FLIR_alligned.
![image](https://github.com/DocF/multispectral-object-detection/assets/13173745/2d77dabb-2c07-4972-abb5-3c8458e4aaa4)

What should I enter in the 4 fields of train_rgb, val_rgb, train_ir, val_ir.
