### ISSUE TITLE
改为最新版本的yolov5框架

### ISSUE THREAD

**Issue by XiangqingZhang** [DocF/multispectral-object-detection#13]
你好，我想把这个代码修改到最新YOLOv5的框架，你有计划更新吗，或者我该修改哪些位置，谢谢

**Comment by DocF** [comment]
抱歉，我最近都没有更新该仓库的计划。
其主要的改动量在于修改yolov5的dataloader，必须保证可见光和红外模态的输入必须是配对的。
也就是说，dataloader的采样必须是一致，并且采用的数据增强也得是一致的（如马赛克增强如果不一致，则会导致输入图像是不配对的）。
此外的网络结构你可以拷贝本仓库。

**Comment by XiangqingZhang** [comment]
好的，感谢
