### ISSUE TITLE
python detect_twostream.py如何同时测试可见光和红外视频

### ISSUE THREAD

**Issue by XiangqingZhang** [DocF/multispectral-object-detection#14]
我将两路视频输入进去，检测结果只保存了可见光的结果，找不到红外检测结果

**Comment by DocF** [comment]
我当时只测试了图片对的输入，并没有测试视频流。
你可能需要修改 detect_twostream.py，以保存其结果。

**Comment by XiangqingZhang** [comment]
好的，我测试了你的model，测试结果中RGB和IR图像画出的boundingbox是一样的，不再进行决策级融合吗？

**Comment by Clustering1** [comment]
您好请问为什么我用了best.pt测试FILR中的图片，上面没有显示预测框呢？
