### ISSUE TITLE
about yolov5s_fusion_add_vedai.yaml

### ISSUE THREAD

**Issue by mzzjuve** [DocF/multispectral-object-detection#16]
According to the image in your paper, the YAML file should be two streams of input RGB image and IR image respectively. Why the input of the second stream [-4, 1, Focus, [64, 3]]，-4 means from layer 6 instead of   IR images? Why not for example [-10,1, Focus, [64, 3]] （of course this will not work）

**Comment by jy-cao** [comment]
Hi, I have the same question. Have you understood why using -4 in [-4, 1, Focus, [64, 3]]? Thanks!

**Comment by Milscao** [comment]
Hi, I have the same question. Have you understood why using -4 in [-4, 1, Focus, [64, 3]]? Thanks!

**Comment by CaoMiles** [comment]
Hi, I have the same question.  Have you understood why using -4 in [-4, 1, Focus, [64, 3]]? Thanks!

**Comment by xinpuliu** [comment]
Hi, I have the same question，do you understand it ?

**Comment by xinpuliu** [comment]
Hi, I have the same question，do you understand it ?
@mzzjuve @CaoMiles

**Comment by Dorablank** [comment]
可以阅读一下yolo_test.py 中的forward_once函数
我的理解是如果m.f索引为-1 输入为x(rgb图像) 
如果m.f索引为-4 输入为x2(ir图像)
