### ISSUE TITLE
您好，能向您要一份您的yolov5 format的LLVIP数据集吗？

### ISSUE THREAD

**Issue by Hiram1026** [DocF/multispectral-object-detection#17]
`# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
train_rgb: /home/fqy/Data/FLIR_ADAS_1_3/align/yolo/rgb/align_train.txt  # 128 images
val_rgb: /home/fqy/Data/FLIR_ADAS_1_3/align/yolo/rgb/align_validation.txt  # 128 images
train_ir: /home/fqy/Data/FLIR_ADAS_1_3/align/yolo/ir/align_train.txt  # 128 images
val_ir: /home/fqy/Data/FLIR_ADAS_1_3/align/yolo/ir/align_validation.txt  # 128 images`
对于这种方式的目录结构和.txt的内容不是很清楚，所以想像你要一份yolov5 format的llvip数据，非常感谢！

**Comment by Hiram1026** [comment]
.txt的label文件是要跟图片在同一个目录里吗

**Comment by Hiram1026** [comment]
已解决

**Comment by XuKer** [comment]
> 
你好，请问你这个转换是怎么操作的？


> 已解决

**Comment by mengyin369** [comment]
> 已解决

你好，请问一下你是如何解决的，我也有这个疑惑
