### ISSUE TITLE
请问您可以提供您所用的VEDAI数据集吗？

### ISSUE THREAD

**Issue by mzzjuve** [DocF/multispectral-object-detection#19]
我最近在跑有关VEDAI和YOLO的实验，但是我所用的数据集标注文件有问题，
![QAES)D3VIO1)GHVU_M$SP~G](https://user-images.githubusercontent.com/92798240/158933224-0409a988-f560-4296-be8e-fd61bfc5c126.png)
如图所示，我认为是我所使用的数据集的问题（因为标注是转换来的），但是我并未发现有什么异常，无法解决。
请问您可以提供您所用的VEDAI数据集吗？或者您是否知道我这个问题该如何解决呢？
感谢您的工作！对您感激不尽！

**Comment by DocF** [comment]
你可以尝试一下多等待几个epoch，由于VEDAI数据集本身体量较小，前几个epoch的mAP等于0属于正常。

**Comment by mzzjuve** [comment]
> 你好，我也遇到了这个情况，所有epoch都跑完之后mAP仍然等于0，请问您解决了吗？

你好，我暂时没有解决，不过由于硬件条件不足我用的是yolov5n和512*512分辨率的输入，可能换个大一点的网络会有效果。
不知道你是不是和我一样

**Comment by HUANG7M** [comment]
好的谢谢，我使用了对齐的数据集，yolov5s和320*320，效果会好一点，您也可以试试先对齐

**Comment by DocF** [comment]
@mzzjuve @HUANG7M 建议先查看训练过程中损失函数是否下降，如果训练集损失函数下降正常；则用detect函数查看一下检测图片输出，有可能是网络的下采样倍数与检测函数设置的倍数不一致，如果是这样情况你会很容易在检测结果图片中发现这种倍数关系。该问题我在后续修改yolov3_transformer模型也曾经遇到。
