### ISSUE TITLE
Could you provide the checkpoint on FLIR dataset?

### ISSUE THREAD

**Issue by socome** [DocF/multispectral-object-detection#20]
Thank you for your nice work. 

I train the model with the option as below :

```
parser.add_argument('--cfg', type=str, default='./models/transformer/yolov5l_fusion_transformerx3_FLIR_aligned.yaml', help='model.yaml path')
```

Then, I can't reproduce the results on FLIR dataset in the paper. 
#### The results of training process
![image](https://user-images.githubusercontent.com/44772344/159687583-f99d0ae9-0e62-4e18-8568-6c6face796d7.png)
#### The result of best checkpoint
![image](https://user-images.githubusercontent.com/44772344/159680667-abd7e536-8565-48f0-91f8-a541e8a8a822.png)

 Could you provide the checkpoint on FLIR dataset? 

Also, i got difference baseline result when i train the add-fusion model.

![image](https://user-images.githubusercontent.com/44772344/159796762-d293406e-cfa7-4479-813f-95da2922003b.png)
![image](https://user-images.githubusercontent.com/44772344/159796897-daef08ad-f98a-4020-a1c5-da2978414c97.png)

**Comment by DocF** [comment]
You'd better set batch szie to 8 and training epochs to 300.

**Comment by socome** [comment]
I tried like you said, but I can't reproduce the results too.  Could you provide the checkpoint on FLIR dataset?

```
    parser.add_argument('--epochs', type=int, default=300)
    parser.add_argument('--batch-size', type=int, default=8, help='total batch size for all GPUs')

```

![image](https://user-images.githubusercontent.com/44772344/160058770-7b5d59ca-9124-4454-bf3e-10d3a57f6477.png)

**Comment by DocF** [comment]
You can download form this website https://drive.google.com/file/d/1PwEOgT5ZOTjoKT2LpOzvCsxsVgwP8NIJ/view
