### ISSUE TITLE
Which model of yoloV5 did you choose for the best results in your paper?

### ISSUE THREAD

**Issue by mzzjuve** [DocF/multispectral-object-detection#21]
yolov5l? or yolov5x/s？sorry,i didn't find in your paper

**Comment by DocF** [comment]
You can see the [config files](https://github.com/DocF/multispectral-object-detection/tree/main/models/transformer/)
FLIR_aligned: yolov5l
LLVIP:yolov5l
VEDAI:yolov5s

**Comment by mzzjuve** [comment]
> You can see the [config files](https://github.com/DocF/multispectral-object-detection/tree/main/models/transformer/) FLIR_aligned: yolov5l LLVIP:yolov5l VEDAI:yolov5s

thank you for your patient reply
