### ISSUE TITLE
请问下训练LLVIP模型的硬件配置和训练时间

### ISSUE THREAD

**Issue by Hiram1026** [DocF/multispectral-object-detection#28]
请问下那个LLVIP 200epch 1024 32bsz 的模型什么硬件环境训练的，训练了多久；
我两张3090估计得2天

**Comment by DocF** [comment]
差不多我用4卡RTX TITAN

**Comment by dyx30** [comment]
您好，我想请问多卡训练需要修改模型的哪些参数。在四张3090的服务器上，我尝试修改了device，但是训练时还是使用单块gpu @Hiram1026  @DocF
