### ISSUE TITLE
有关网络训练的问题

### ISSUE THREAD

**Issue by infinite013** [DocF/multispectral-object-detection#3]
请问您训练的时候迭代了多少epoch，我看您并没有在论文中提及
我将cft移植到分割任务中时，我发现训练的效果不是很好，而且loss波动剧烈
![image](https://user-images.githubusercontent.com/37789662/142092353-f35ce804-4ccb-4525-b986-3cf1207269a6.png)

**Comment by DocF** [comment]
不同的训练数据体量不太一样，几万张图像的训练集大概100epoch，几千张图像的300-400epoch。
分割任务loss波动我不太清楚，但你可以先确认下，两种模态的数据集图片是不是配对输入，这个很关键，直接影响结果。

**Comment by DocF** [comment]
不同体量训练数据的训练轮数不一样，几万张图像的训练集大概100epoch，几千张图像的300-400epoch；另外和自身模型大小也有关系。
分割任务loss波动我不太清楚，但是你可以先可视化下，两种模态的数据集图片是不是配对输入，这个很关键。

**Comment by x-fish-min** [comment]
您好，我也想问您在训练FLIR-aliged、LLVIP和VEDAI这几个数据集时分别使用多少个epoch呢？

**Comment by x-fish-min** [comment]
另外，请问您在训练时是否使用了预训练模型？还是从头训练的？

**Comment by x-fish-min** [comment]
> 不同体量训练数据的训练轮数不一样，几万张图像的训练集大概100epoch，几千张图像的300-400epoch；另外和自身模型大小也有关系。 分割任务loss波动我不太清楚，但是你可以先可视化下，两种模态的数据集图片是不是配对输入，这个很关键。

您好，我也想问您在训练FLIR-aliged、LLVIP和VEDAI这几个数据集时分别使用多少个epoch呢？另外，请问您在训练时是否使用了预训练模型？还是从头训练的？
