### ISSUE TITLE
关于找不到FFVIP的缓存图片

### ISSUE THREAD

**Issue by cenchaojun** [DocF/multispectral-object-detection#31]
![image](https://user-images.githubusercontent.com/48192514/166114784-b35c8766-4a8d-4875-9140-b0c59b2b4bbe.png)
请问这个是什么原因，数据集的格式应该是什么样子的

**Comment by cenchaojun** [comment]
已经调试解决

**Comment by mengyin369** [comment]
请问一下你解决了吗？我也在这里出问题了

**Comment by mengyin369** [comment]
> 已经调试解决

请问一下你是如何解决的，我也有这个疑惑
