### ISSUE TITLE
关于模型训练的具体设置

### ISSUE THREAD

**Issue by x-fish-min** [DocF/multispectral-object-detection#4]
您好，我也想问您在训练FLIR-aliged、LLVIP和VEDAI这几个数据集时分别使用多少个epoch呢？另外，请问您在训练时是否使用了预训练模型？还是从头训练的？

**Comment by DocF** [comment]
你可以查看比如 训练的权重 yolov5l_transformerx3_llvip_s1024_bs32_e200，表示LLVIP上使用1024输入，batchsize32，epoch200。FLIR-aligned 用了640输入，batchsize32，300epoch。
我是加载YOLOv5提供的权重进行训练的。

**Comment by x-fish-min** [comment]
感谢您的回复！那么您在单独使用可见光或红外数据训练单模态的模型作为对照时，所采用参数设置与训练融合模型是否一致呢？

**Comment by DocF** [comment]
对照组是使用add的融合检测模型，训练参数设置一致。

**Comment by x-fish-min** [comment]
哦我指的是对照组中的单模态模型，也就是您使用官方（ultralytics）的YOLOv5或者YOLOv3代码分别训练可见光和红外数据时的设置。我没太理解您说的"add的融合检测模型"是指什么，在您的论文中好像没看到这组对照

**Comment by DocF** [comment]
4.3消融实验小节中的对照组并非是单模态，而是使用结构two-stream的YOLOv5（与论文图2的模型唯一区别就是没有使用CFT模块），此时该模型使用add操作进行模态特征融合的，这部分请参考4.2.小节的原文，抱歉可能在论文中没有讲清楚，引起了歧义。
> In these experiments, YOLOv5 is chosen as our base detector. By adding an additional branch for the extraction
of thermal features, it is transformed into a two-stream convolutional neural network, as illustrated in Fig. 2.

你说的单模态应该是指4.4.Comparison with State-of-the-art Methods小节的问题，其中FLIR-aligned和VEDAI数据集结果来自我们的训练结果（其参数与CFT训练保持一致），LLVIP的结果则是LLVIP数据集原论文提供的。

**Comment by x-fish-min** [comment]
好的，感谢您的解答。

**Comment by DocF** [comment]
不客气
