### ISSUE TITLE
RuntimeError: result type Float can't be cast to the desired output type long int

### ISSUE THREAD

**Issue by minkyukang707** [DocF/multispectral-object-detection#47]
I tried to run this code with LLVIP dataset. But I encountered this error. I searched it on Google then I saw that this is YOLOv5 version matter but I couldn't understand.  

I installed requirements.txt and I used this on Colab

I put my running progress 

#####
Transferred 207/1445 items from yolov5l.pt
Scaled weight_decay = 0.0005
Optimizer groups: 372 .bias, 372 conv.weight, 174 other
train: Scanning '/content/drive/MyDrive/0201_asd/multispectral-object-detection/custom/rgb_sum/autosplit_train' images and labels... 39 found, 0 missing, 0 empty, 0 corrupted: 100% 39/39 [00:12<00:00,  3.17it/s]
train: New cache created: /content/drive/MyDrive/0201_asd/multispectral-object-detection/custom/rgb_sum/autosplit_train.cache
train: Scanning '/content/drive/MyDrive/0201_asd/multispectral-object-detection/custom/therm_sum/autosplit_train' images and labels... 42 found, 0 missing, 0 empty, 0 corrupted: 100% 42/42 [00:12<00:00,  3.27it/s]
train: New cache created: /content/drive/MyDrive/0201_asd/multispectral-object-detection/custom/therm_sum/autosplit_train.cache
0.0
val: Scanning '/content/drive/MyDrive/0201_asd/multispectral-object-detection/custom/rgb_sum/autosplit_val' images and labels... 5 found, 0 missing, 0 empty, 0 corrupted: 100% 5/5 [00:01<00:00,  3.27it/s]
val: New cache created: /content/drive/MyDrive/0201_asd/multispectral-object-detection/custom/rgb_sum/autosplit_val.cache
val: Scanning '/content/drive/MyDrive/0201_asd/multispectral-object-detection/custom/therm_sum/autosplit_val' images and labels... 2 found, 0 missing, 0 empty, 0 corrupted: 100% 2/2 [00:00<00:00,  3.49it/s]
val: New cache created: /content/drive/MyDrive/0201_asd/multispectral-object-detection/custom/therm_sum/autosplit_val.cache
Plotting labels... 

autoanchor: Analyzing anchors... anchors/target = 5.53, Best Possible Recall (BPR) = 1.0000
Image sizes 640 train, 640 test
Using 0 dataloader workers
Logging results to runs/train/exp
Starting training for 100 epochs...

     Epoch   gpu_mem       box       obj       cls     total    labels  img_size
  0% 0/10 [00:22<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 1010, in <module>
    train_rgb_ir(hyp, opt, device, tb_writer)
  File "train.py", line 758, in train_rgb_ir
    loss, loss_items = compute_loss(pred, targets.to(device))  # loss scaled by batch_size
  File "/content/drive/MyDrive/0201_asd/multispectral-object-detection/utils/loss.py", line 117, in __call__
    tcls, tbox, indices, anchors = self.build_targets(p, targets)  # targets
  File "/content/drive/MyDrive/0201_asd/multispectral-object-detection/utils/loss.py", line 211, in build_targets
    indices.append((b, a, gj.clamp_(0, gain[3] - 1), gi.clamp_(0, gain[2] - 1)))  # image, anchor, grid indices
RuntimeError: result type Float can't be cast to the desired output type long int
#####

How could I solve this? Should install other version of Pytorch or Yolov5? I git cloned yolov5 again but LLVIP.yaml makes an error while on train.py

**Comment by minkyukang707** [comment]
I solved above error by installing torch 1.11.0 version 

But I got another error 

------
Transferred 207/1445 items from yolov5l.pt
Scaled weight_decay = 0.0005
Optimizer groups: 372 .bias, 372 conv.weight, 174 other
train: Scanning RGB '/content/drive/MyDrive/0201_asd/multispectral-object-detection/custom/rgb_sum/autosplit_train.cache' images and labels... 39 found, 0 missing, 0 empty, 0 corrupted: 100% 39/39 [00:00<?, ?it/s]
train: Scanning IR '/content/drive/MyDrive/0201_asd/multispectral-object-detection/custom/rgb_sum/autosplit_train.cache' images and labels... 42 found, 0 missing, 0 empty, 0 corrupted: 100% 42/42 [00:00<?, ?it/s]
0.0
val: Scanning RGB '/content/drive/MyDrive/0201_asd/multispectral-object-detection/custom/rgb_sum/autosplit_val.cache' images and labels... 5 found, 0 missing, 0 empty, 0 corrupted: 100% 5/5 [00:00<?, ?it/s]

val: Scanning IR '/content/drive/MyDrive/0201_asd/multispectral-object-detection/custom/rgb_sum/autosplit_val.cache' images and labels... 2 found, 0 missing, 0 empty, 0 corrupted: 100% 2/2 [00:00<?, ?it/s]
Plotting labels... 

autoanchor: Analyzing anchors... anchors/target = 5.53, Best Possible Recall (BPR) = 1.0000
Image sizes 640 train, 640 test
Using 0 dataloader workers
Logging results to runs/train/exp3
Starting training for 100 epochs...

     Epoch   gpu_mem       box       obj       cls     total    labels  img_size
      0/99     7.72G    0.1136   0.05542         0     0.169        17       640: 100% 10/10 [00:32<00:00,  3.30s/it]
               Class      Images      Labels           P           R      mAP@.5     mAP@.75  mAP@.5:.95:   0% 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 1010, in <module>
    train_rgb_ir(hyp, opt, device, tb_writer)
  File "train.py", line 812, in train_rgb_ir
    results, maps, times = test.test(data_dict,
  File "/content/drive/MyDrive/0201_asd/multispectral-object-detection/test.py", line 104, in test
    for batch_i, (img, targets, paths, shapes) in enumerate(tqdm(dataloader, desc=s)):
  File "/usr/local/lib/python3.8/dist-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/content/drive/MyDrive/0201_asd/multispectral-object-detection/utils/datasets.py", line 281, in __iter__
    yield next(self.iterator)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 530, in __next__
    # try to compute a suggested max number of worker based on system's resource
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 570, in _next_data
    shared_rng.manual_seed(self._shared_seed)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    super(_MapDatasetFetcher, self).__init__(
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    super(_MapDatasetFetcher, self).__init__(
  File "/content/drive/MyDrive/0201_asd/multispectral-object-detection/utils/datasets.py", line 1158, in __getitem__
    index_ir = self.indices_ir[index]  # linear, shuffled, or image_weights
IndexError: range object index out of range
-------

I chechked index but I couldn't get it. Where should I fix it?

**Comment by anilcanbulut** [comment]
This is most likely related to the path of the Thermal images. You can confirm that by making a debug in the related part of the code and seeing whether the path you have given for both RGB and Thermal images is correct. The file name-checking system in the code is a little tricky. It uses the same name coming from the RGB images for the Thermal image name creation. In the beginning, I was using different named RGB and Thermal images and once I changed their names and made them the same, the error disappeared.

**Comment by minkyukang707** [comment]
@anilcanbulut 
Ok I'll try that :) Teşekkür ederim

**Comment by minkyukang707** [comment]
I solved it. It's matter of data length between RGB adn IR. Length of RGB was 40, and length of IR was 42. After i found it I modified datasets, and it worked. But the performance was so bad i don't know why, I'm figuring out now

**Comment by rorubyy** [comment]
I also encounter the problem "RuntimeError: result type Float can't be cast to the desired output type long int", and I solved it use [this solution](https://rorubyy.notion.site/RuntimeError-result-type-Float-can-t-be-cast-to-the-desired-output-type-long-int-b296897b833840cb9a7086a76a576d64)

**Comment by tj-messi** [comment]
@rorubyy @minkyukang707 RuntimeError: result type Float can't be cast to the desired output type long int

how can i solve it？
