### ISSUE TITLE
测试结果map过高

### ISSUE THREAD

**Issue by zx0v0** [DocF/multispectral-object-detection#50]
刚入门复现代码，我根据提供地址下载了FLIR数据集之后，通过Roboflow平台转换为Yolo txt格式并分为train，valid，test三部分，以batchsize=32，epoch=200训练，之后进行测试，但是test的map@0.5达到了0.98，请问有人遇到过这种情况吗？

**Comment by a1997-dom** [comment]
原论文是按epoch=100训练的，不过我按batchsize=8训练也要比原论文结果要好，搞不太清楚什么原因。可以留个联系方式交流一下吗

**Comment by zx0v0** [comment]
> 原论文是按epoch=100训练的，不过我按batchsize=8训练也要比原论文结果要好，搞不太清楚什么原因。可以留个联系方式交流一下吗

你好～我也还在尝试，我的QQ是739696467
