### ISSUE TITLE
关于自建数据集的处理形式

### ISSUE THREAD

**Issue by MrReeed** [DocF/multispectral-object-detection#7]
您好，很荣幸能拜读您的文章和程序，想请教一下如果我想自己制作数据集，应该如何将图片处理成这种黑白形式的多光谱图片呢？自建数据集的话在多光谱图像的参数上有没有需要注意的点呢，谢谢您

**Comment by DocF** [comment]
感谢您关注我们的工作，关于”自建数据集图片如何处理成这种黑白形式的多光谱图片“的问题，我们本身并没有构建自身数据集，而是使用已经开源的数据进行验证。在这些数据集中，黑白形式图是代表红外模态，本质上就是简单的灰度图。

另外参数的话，我们的建议是根据数据规模选择不同大小的模型，如在论文中对于数据集较小的VEDAI（~1000张）我们使用了YOLOV5small为基线的CFT模型，而对于相对较大的LLVIP（~17000）和FLIR（~5000）我们使用了YOLOV5large为基线的CFT模型。

再次感谢您对我们工作的关注，也欢迎您引用我们的工作。

**Comment by MrReeed** [comment]
非常感谢您耐心和仔细地回复我，对我来说受益匪浅。您的文章研究思路很不错，我将尝试在我的研究中融入您的方法，如果顺利将引用您的研究方法，再次感谢您。

**Comment by DocF** [comment]
好的 那我们将关闭这个issue

**Comment by MrReeed** [comment]
你好！邮件我已收到，谢谢~
